# Constructing matrices for multiqubit quantum gates

The goal of this article is to show how quantum gates are represetned by the matrices, and how to build appropitate matrices to act on a single qubit in multiqubit entlaged system.


## Introduction

*Latex math*
$$ \def\ket#1{\lvert #1 \rangle}\def\bra#1{\langle #1 \rvert} $$

The quantum computing based on a quantum gates are basing on the matrix calculation. The quantum state is represnetd by the vector and the gates are the matrieces that acts over the state [suskind].

The two basic states that represents `0` and `1` are:

$ \left| 0 \right\rangle = {\begin{bmatrix}1 \\ 0\end{bmatrix}} $,

$ \left| 1 \right\rangle = {\begin{bmatrix}0 \\ 1\end{bmatrix}} $.

The qubyte that consist of two qubits is represented by two bytes.

$ \ket{01} = \left| 0 \right\rangle \otimes \left| 1 \right\rangle 
= {\begin{bmatrix}1 \\ 0\end{bmatrix}} \otimes {\begin{bmatrix}0 \\ 1\end{bmatrix}} 
= {\begin{bmatrix}1 \\ 0\end{bmatrix}}  {\begin{bmatrix}0 \\ 1\end{bmatrix}}^{T}
= {\begin{bmatrix}1 \\ 0\end{bmatrix}} {\begin{bmatrix}0 & 1\end{bmatrix}}
= {\begin{bmatrix}0\\ 1 \\ 0 \\ 0\end{bmatrix}} 
$


## Python intialization

In [6]:
import numpy as np

# |0>, |1>
Zero = np.array([[1.],
                 [0.]]) 

One = np.array([[0.],
                [1.]]) 

ZeroOne = np.array([[0.],
                    [1.],
                    [0.],
                    [0.],]) 

## One qubit gate in multi-qubit system

There are serveral on qubit gates the Hadamard gate (H), Pauli's gate, Identity. You can learn more about one qubit gate in the [Qiskit textbook](http://). Let's use the Pauli's X gate for the following example.

The Pauli X gate makes the qbit flip it state. It is represented by the matrix:

$ X = {\begin{bmatrix}0 & 1\\1 & 0\end{bmatrix}} $,


Appling this gate on the qubit in the $ \ket{0} $ state results in $ \ket{1} $ state:


$ X\left| 0 \right\rangle = {\begin{bmatrix}0 & 1\\1 & 0\end{bmatrix}} {\begin{bmatrix}1 \\ 0\end{bmatrix}} = {\begin{bmatrix}0 \\ 1 \end{bmatrix}} = \left| 1 \right\rangle$,

Using the numpy:

In [5]:
X = np.array([[0, 1],
              [1, 0]])

np.dot(X, Zero)

array([[0.],
       [1.]])

But how to perform the same operation if we have got a two qubit system? For exmaple in qubyte:

$$ \ket{01} = \begin{bmatrix}0\\ 1 \\ 0 \\ 0\end{bmatrix} $$

we only want to flip the first qbit to receive:

$$ \ket{11} = \begin{bmatrix}0\\ 0 \\ 0 \\ 1\end{bmatrix} $$


$$ X_a \ket{01} = \ket{11} $$ 

How to construct the matrix $X_a$ that makes the calculation?

We need to construct $X_a$ gate using the Identity to flip only the first qubit and leave the second untouched.

$$ I = {\begin{bmatrix}1 & 0\\0 & 1\end{bmatrix}} $$

$$ X_a = X \otimes I = 
\begin{bmatrix} 
0 & 0 & 1 & 0 \\ 
0 & 0 & 0 & 1 \\ 
1 & 0 & 0 & 0 \\ 
0 & 1 & 0 & 0 \end{bmatrix}
$$

$$ X_a\ket{01} = 
\begin{bmatrix} 
0 & 0 & 1 & 0 \\ 
0 & 0 & 0 & 1 \\ 
1 & 0 & 0 & 0 \\ 
0 & 1 & 0 & 0 
\end{bmatrix} 
\begin{bmatrix}0\\ 1 \\ 0 \\ 0\end{bmatrix} 
= 
\begin{bmatrix}0\\ 0 \\ 0 \\ 1\end{bmatrix}
= \ket{11}
$$

Of course if we would like to flip the *b* qubit we need to construct the $X_b$ gate swaping the X and I gate:

$$ X_b = I \otimes X = 
\begin{bmatrix} 
0 & 1 & 0 & 0 \\ 
1 & 0 & 0 & 0 \\ 
0 & 0 & 0 & 1 \\ 
0 & 0 & 1 & 0 
\end{bmatrix}
$$

$$ X_b\ket{01} = 
\begin{bmatrix} 
0 & 1 & 0 & 0 \\ 
1 & 0 & 0 & 0 \\ 
0 & 0 & 0 & 1 \\ 
0 & 0 & 1 & 0 
\end{bmatrix}
\begin{bmatrix}0\\ 1 \\ 0 \\ 0\end{bmatrix} 
= 
\begin{bmatrix}1\\ 0 \\ 0 \\ 0\end{bmatrix}
= \ket{00}
$$

To extend this approach for the more qubits we need to construct the matrix (M) using the tensor product with Identity and the desierd gate (G), where the desiered gate is placed in the equation on the postion corresponding the qubit in the system:

$$ M = I \otimes I \otimes .... \otimes G \otimes ... \otimes I $$


The general idea of constructing the matrix for the qubit gates in the multi-qubit system is to make the tensor product of the gates, placing the Identity gate for the qubits that should not be changed.

For example if we would like to apply Hadamard for the all qubits in the three qubit system we should prepare the matrix:

$$ M = H \otimes H \otimes H $$


## Matrix representation of two qubit gate

How to perfrom the calcustion on a qubyte that consists of two qubits?
CNOT gate

## Constructing matrices for 4 qubit system

CNOT for 4 qubit system

In [ ]:

# 3-qubit Hadamard gate
Hq012 = np.kron(np.kron(H,H),H)

# 3-qubit CZ gates
p00 = zero * np.array([1, 0]) # |0><0|
p11 = one * np.array([0, 1]) # |1><1|
# control = 1 (|0><0| + |1><1|), target = 0 (Z), uninvoled =2 (I)
# 012 + 012 - qubit indexint
cz10 = np.kron(np.kron(I, p00), I) + np.kron(np.kron(Z, p11), I)
cz20 = np.kron(np.kron(I, I), p00) + np.kron(np.kron(Z, I), p11)

# 3-qubit CCZ gate
# control = (|0><0| + |1><1|), 
# target = (Z)
# control = 21
# target  = 0 
ccz210 = np.kron(np.kron(I, p00), p00) + np.kron(np.kron(Z, p11), p11)


https://quantumcomputing.stackexchange.com/a/4255

In [1]:
import numpy as np
from qiskit.extensions import HGate, CnotGate, IdGate, XGate, CzGate, ZGate

# We can build the matrix on our own
H = 1./np.sqrt(2) * np.array([[1, 1],
                              [1, -1]])

# or just import it from qiskit
I = IdGate().to_matrix()

Hq0 = np.kron(np.kron(H,I), I)
Hq1 = np.kron(np.kron(I,H), I)
Hq2 = np.kron(np.kron(I,I), H)
Hq012 = np.kron(np.kron(H,H),H)



In [2]:
import numpy as np
zero = np.array([[1.],
                 [0.]]) 

state = np.kron(np.kron(zero, zero), zero)
state

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [3]:
np.dot(Hq012, state)

array([[0.35355339],
       [0.35355339],
       [0.35355339],
       [0.35355339],
       [0.35355339],
       [0.35355339],
       [0.35355339],
       [0.35355339]])

Step by step

In [4]:
state = np.dot(Hq0, state)
print(state)
state = np.dot(Hq1, state)
print(state)
state = np.dot(Hq2, state)
print(state)

[[0.70710678+0.j]
 [0.        +0.j]
 [0.        +0.j]
 [0.        +0.j]
 [0.70710678+0.j]
 [0.        +0.j]
 [0.        +0.j]
 [0.        +0.j]]
[[0.5+0.j]
 [0. +0.j]
 [0.5+0.j]
 [0. +0.j]
 [0.5+0.j]
 [0. +0.j]
 [0.5+0.j]
 [0. +0.j]]
[[0.35355339+0.j]
 [0.35355339+0.j]
 [0.35355339+0.j]
 [0.35355339+0.j]
 [0.35355339+0.j]
 [0.35355339+0.j]
 [0.35355339+0.j]
 [0.35355339+0.j]]


$$
\begin{alignat}{2}
\mathit{CX}_{1,3} \;&amp;=&amp;\;
\underbrace{\ket{0}\!\bra{0}}_{\text{control}} \otimes \underbrace{\;\mathbf 1_2\;}_{\!\!\!\!\text{uninvolved}\!\!\!\!} \otimes \underbrace{\;\mathbf 1_2\;}_{\!\!\!\!\text{target}\!\!\!\!}
&amp;+\,
\underbrace{\ket{1}\!\bra{1}}_{\text{control}} \otimes \underbrace{\;\mathbf 1_2\;}_{\!\!\!\!\text{uninvolved}\!\!\!\!} \otimes \underbrace{\; X\;}_{\!\!\!\!\text{target}\!\!\!\!}
\\[1ex]&amp;=&amp;\;
\begin{bmatrix}
  \mathbf 1_2 &amp; \mathbf 0_2 &amp; \phantom{\mathbf 0_2} &amp; \phantom{\mathbf 0_2} \\
  \mathbf 0_2 &amp; \mathbf 1_2 &amp; \phantom{\mathbf 0_2} &amp; \phantom{\mathbf 0_2} \\
  \phantom{\mathbf 0_2} &amp; \phantom{\mathbf 0_2} &amp; \phantom{\mathbf 0_2} &amp; \phantom{\mathbf 0_2} \\
  \phantom{\mathbf 0_2} &amp; \phantom{\mathbf 0_2} &amp; \phantom{\mathbf 0_2} &amp; \phantom{\mathbf 0_2}
\end{bmatrix}
\,&amp;+\,
\begin{bmatrix}
  \phantom{\mathbf 0_2} &amp; \phantom{\mathbf 0_2} &amp; \phantom{\mathbf 0_2} &amp; \phantom{\mathbf 0_2} \\
  \phantom{\mathbf 0_2} &amp; \phantom{\mathbf 0_2} &amp; \phantom{\mathbf 0_2} &amp; \phantom{\mathbf 0_2} \\
  \phantom{\mathbf 0_2} &amp; \phantom{\mathbf 0_2} &amp; X &amp; \mathbf 0_2 \\
  \phantom{\mathbf 0_2} &amp; \phantom{\mathbf 0_2} &amp; {\mathbf 0_2} &amp; X
\end{bmatrix}
\end{alignat}
$$